---
title: "BayesTest"
output: html_document
---
```{r}
library(TeachBayes)

Prior_beta=c(2.9,2)
beta_draw(Prior_beta)
```

Binomial dist
```{r}
n=150
k=seq(0,n, by=1)
sim_binom=dbinom(k, size=n, prob=0.466)

plot(k, sim_binom)
```


```{r}
a=2.9+70
b=2.0+80
Posterior_beta=c(a,b )

beta_prior_post(Prior_beta, Posterior_beta)
```


simulate from posterior distribution
```{r}
Posterior_sim=rbeta(5000, a,b)
hist(Posterior_sim, breaks=30)
```

mean for beta dist = a/(a+b)
```{r}
a/(a+b)
```


Only allow 20% chance we run out of food, so want to know quantile where 20% is area above this point.
```{r}
qbeta(.8, a, b) #posterior
```

```{r}
qbeta(0.8, 2.9,2 ) #prior

qbinom(.8, size=150, prob=.466)
```

```{r}
Models=c(0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9)
Priors=round(c(1/8, 1/8, 1/8, 2/8, 1/8, 1/8, 1/8),2)

df=data.frame(Models, Priors)
rownames(df)=c("p=0.3", "p=0.4", "p=0.5", "p=0.6", "p=0.7", "p=0.8", "p=0.9")

df$Liklihood=dbinom(70, size=150, prob=Models)
df$Product = df$Priors*df$Liklihood
df$Posterior=df$Product/sum(df$Product)

df2=df[c("Models", "Posterior")]
```

