---
title: "TDI interview"
author: "Natalie Morse"
date: "May 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

install.packages(c("ggplot2", "dplyr", "sciplot", "repr", "VennDiagram"))
library(VennDiagram)
```

```{r}

criticalvaluelow=qt(.025, 15)
criticalvaluehigh=qt(.975, 15)

draws <- rt(100000, df=15)
dens <- density(draws)
criticalvaluelow1=quantile(draws, .025)
criticalvaluehigh1=quantile(draws, .975)

left=max(which(dens$x<=-4)) #zero, or starting point x3
indexlow=max(which(dens$x <=criticalvaluelow1)) #critical value low, the area between left and indexlow should be 0.025 (half the allowable 0.05)
indexhigh=min(which(dens$x >=criticalvaluehigh1)) #critical value high x1
right=max(which(dens$x<4)) #end. The area between indexhigh and right should be 0.025


#curve(dt(x, df=15), -4,4)
plot(dens, xlim=c(-4,4))
with(dens, polygon(x=c(x[c(left,left:indexlow,indexlow)]), y= c(0, y[left:indexlow], 0), col="gray")) #low tail

with(dens, polygon(x=c(x[c(indexhigh,indexhigh:right,right)]), y= c(0, y[indexhigh:right], 0), col="gray")) #high tail
```


```{r}
set.seed(1)
draws <- rnorm(100)^2
dens <- density(draws)
plot(dens)

q2     <- 2
q65    <- 6.5
qn08   <- -0.8
qn02   <- -0.2

x1 <- min(which(dens$x >= q2))  
x2 <- max(which(dens$x <  q65))
x3 <- min(which(dens$x >= qn08))  
x4 <- max(which(dens$x <  qn02))

with(dens, polygon(x=c(x[c(x1,x1:x2,x2)]), y= c(0, y[x1:x2], 0), col="gray"))
```


```{r}
draw.pairwise.venn(15, 15, 5, category = c("Jets Win", "Star hurt"), lty = rep("blank", 
2), fill = c("blue", "red"), alpha = rep(0.5, 2), cat.pos = c(0, 
0), cat.dist = rep(0.025, 2), scaled = FALSE)
```


## Monte carlo simulations

proportion of town that will come to concert.
Use binomial where success is 'attend' and fail = will not come to concert.
```{r}
rbinom()
```


```{r}
geneq <- function(x) rt(1,0.5)
f <- function(x) dt(x,1)
q <- function(y,x){
  dt(x,0.5)
}
x <- vector()
x[1] <- 1
y=vector()

for(t in 1:500){
  y[t] <- geneq ( x[t] )
  if( runif(1) < f(y) * q(y,x[t])/ ( f(x[t]) * q(x[t],y))){
    x[t+1]=y
  }else{
    x[t+1]=x[t]
  }
}

head(y)
```


```{r}
#from book
#this works, but not sure why do not get multiple ys, we do get multiple xs
f <- function(x) dt(x,1)
q <- function(y,x){
  dt(x,0.5)
}
geneq <- function(x) rnorm(n=100, mean=0.6, sd=0.2)
t=c(1:500)
y=vector()
x=vector()
x[1]=1

if (runif(1)<f(y)*q(y,x[t])/(f(x[t])*q(x[t],y))){
x[t+1]=y
}else{
x[t+1]=x[t]
}

head(x)

```

https://www4.stat.ncsu.edu/~reich/st740/Computing3.pdf
```{r}
#bookkeeping
n <- length(y)
sumy <- sum(y)
iters=200
keepers <- matrix(0,iters,2)

#initial values
z <- rep(1,n)
theta <- 0.5
lambda <- 1
for(i in 1:iters){
#update z
P1 <- ifelse(y==0,1,0)*theta
P0 <- dpois(y,lambda)*(1-theta)
z <- rbinom(n,1,P1/(P1+P0))
#update theta and lambda
n1 <- sum(z==1)
n0 <- n-n1
theta <- rbeta(1,a+n1,b+n0)
lambda <- rgamma(1,c+sumy,d+n0)
keepers[i,]<-c(theta,lambda)
}

```

